### ISSUE TITLE
Information Architecture - Site Topology

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-usage-docs#10]
#### Article suggestion

Why do you need to think about your site topology, even in the flat, modern world? How is it different than classic SharePoint? How important are things like name spacing and naming conventions?

**Comment by hugoabernier** [comment]
Put me in coach!

**Comment by sympmarc** [comment]
You’re in! Thanks for picking this one up.

**Comment by sympmarc** [comment]
How's it going, my man?
