### ISSUE TITLE
Designing for Scale

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-usage-docs#16]
#### Article suggestion

Quite often, i see a fair amount of small recipes for SharePoint configuration but not configuration at scale. 

So some suggestions, 

- Architecting for scale such as sites, lists, metadata, apporaches and best practices
- Scripting for scale, ensuring consistency in your implementations

Most implementations are bigger than the unit and I don't see often any info on this. 
This might be a series rather than a single article.

**Comment by sympmarc** [comment]
@pkbullock - this is a great idea. It sounds like you're suggesting advice for citizen devs about how to think on a larger scale than just the particular solution they are building at the time.

If you have ideas you'd like to put down to start an article or two, that would be great.

**Comment by pkbullock** [comment]
@sympmarc yes, when i build solutions often involves hundreds of sites, libraries, etc so i need to think how to build this, what aspects to consider, which SharePoint features can help think on a grander scale.

There is a lot of cross over with some of the other suggestions, so still thinking about this, perhaps that might be a general consideration article.  Happy for you to assign to me, perhaps writing an initial PR on the subject to help sprawl experience and ideas.

**Comment by pkbullock** [comment]
Articles related are #18, #21, #20, #19 to start with.

**Comment by pkbullock** [comment]
please assign to me.
