### ISSUE TITLE
Pull request to suggest an article in the documentation

### ISSUE THREAD

**Issue by jeffangama** [SharePoint/sp-usage-docs#17]
Do you accept pull request to improve the documentation ?
Maybe you can pre-validate the topic we want to submit using this issue system ?
Thank you,

**Comment by sympmarc** [comment]
@jeffangama - yes, of course we will be accepting pull requests. My instructions here are geared more to the people who have not used Github before, which I expect will be a large percentage of the contributors.

As for pre-validating topics, yes. Raising an issue about a topic you would like to cover gives us a chance to have some discussion to refine the idea if it is helpful.

**Comment by sympmarc** [comment]
Answered?
