### ISSUE TITLE
Versioning: lists, libraries, major vs minor, defaults, and best practices/pitfalls

### ISSUE THREAD

**Issue by PatD** [SharePoint/sp-usage-docs#31]
#### Article suggestion

Difference between major/minor versions, what defaults are set to, and how to work with and restore old ones. Best practice guide for lists and libraries.

**Comment by PatD** [comment]
Happy to take this one.

**Comment by sympmarc** [comment]
Thanks, Pat!

**Comment by PatD** [comment]
Ok to add this one one to the TOC?

**Comment by sympmarc** [comment]
Absolutely. Sorry I missed it. Gives us something else to tweet (etc.) about!

**Comment by sympmarc** [comment]
Added to TOC along with some minor edits. Closing this issue...
