### ISSUE TITLE
Benefits of using PowerShell with SharePoint

### ISSUE THREAD

**Issue by veronicageek** [SharePoint/sp-usage-docs#33]
**Article suggestion**
Benefits of using PowerShell with SharePoint

Talk about the different modules available for SharePoint on-prem & SPO, what's the purpose of using PowerShell, why is it so important nowadays, etc..

**Comment by veronicageek** [comment]
More than happy to work on that one 😄

**Comment by sympmarc** [comment]
This one is interesting, as it straddles the citizen developer role and the "IT Pro" role. Interested to see what you come up with!

**Comment by sympmarc** [comment]
Thanks for the submission. Closing for now...
