### ISSUE TITLE
Library scenarios

### ISSUE THREAD

**Issue by tomresing** [SharePoint/sp-usage-docs#5]
Got a great end to end scenario for using SharePoint libraries? We could establish some community practices and patterns.

**Comment by sympmarc** [comment]
Thanks, @tomresing. First issue! One thing this shows me is that I need to build an issue template like the other projects have.

Is this a real gap in the current documentation you'd like to fill? (Or is it an "Is this thing on???"?) If so, I can try to find someone to write something up.

**Comment by tomresing** [comment]
You're welcome! And, I agree on the template. Great idea.
Unless you know of content like this (there's a huge set of content on libraries), I think it's a real gap. 
Do you agree that the perspective of SharePoint practitioners is value for real world patterns and practices like this? I feel like this is the right type of thing for this group.

**Comment by tomresing** [comment]
The template here might work https://github.com/SharePoint/sp-dev-docs/issues/new

**Comment by sympmarc** [comment]
Just checking. Let's see if we can get some content going for this.

I just created a new issue template. Take a look and let me know what you think.

**Comment by tomresing** [comment]
Thanks. Template looks good.

**Comment by nyoung30** [comment]
Hi @tomresing & @sympmarc, I'll try to take this one on.

**Comment by sympmarc** [comment]
Great! Assigning to you...

**Comment by nyoung30** [comment]
Hi @tomresing  & @sympmarc, where would you suggest I put my content "/docs/basics" or "/docs/making decisions"?

**Comment by sympmarc** [comment]
@nyoung30 - Those directories were my early stab at some potential groupings. Feel free to just put it into /docs if you're not sure. We're rapidly getting to a point where we'll need to think about what other buckets we need.

**Comment by nyoung30** [comment]
Hi @tomresing & @sympmarc,

I have a first draft complete of library scenarios. I am planning on additional scenarios but more work is required on my end. 

I've done this work in a "bubble". Could someone review and provide feedback? Also, am I OK to "pull" my first draft into the "master"?

Sorry for all the questions. This (GitHub) is new to me.

Thanks.

Norm

**Comment by tomresing** [comment]
Yes. Please submit a pull request. 

------
Tom Resing

**Comment by sympmarc** [comment]
@nyoung30 - you can just issue a pull request. I'm the only admin at the moment, so I can review if you'd like.

**Comment by nyoung30** [comment]
@tomresing & @sympmarc - Can you please review and let me know if this is what you were looking for? I'm happy to schedule time via Teams. Thanks.

**Comment by sympmarc** [comment]
@nyoung30 - I just read through the article. I think it's really helpful. It was @tomresing's original ask, so I'll defer to him as to whether it meets his needs.

**Comment by tomresing** [comment]
I gave it a read through and agree it provides helpful scenarios for adding document libraries to an existing site. I really didn't have anything specific in mind, other than seeding the pool of ideas for PnP usage. In general, I'd love to see more list and library scenarios added over time. For example, with the fast growth of Microsoft Teams, scenarios may be different that interacting with sites just through the web browser. Would that change what scenarios we'd recommend?

**Comment by tomresing** [comment]
I think I'll close this one for now, since it wasn't very specific and something new was added, which was the goal. If the community needs more ideas added to the pool in the future, I could add more.

**Comment by tomresing** [comment]
Thanks @nyoung30 and @sympmarc!

**Comment by nyoung30** [comment]
Thanks for the feedback @tomresing and @sympmarc. I know there is room for improvement in my writing style, so feedback is welcome.

I'm looking forward to contributing more!

Thanks.

Norm

**Comment by sympmarc** [comment]
I'm hoping the community becomes active here and we get into a collaborative editing mode. :)  I appreciate you jumping in!

Veronique Palmer just did a [post](https://veroniquepalmer.com/2019/10/01/rock-photo-albums-on-modern-sharepoint/) with a cool scenario for lists. I've asked her if she'd like to contribute. These scenario-based articles will be really helpful to people, I think - especially those newer to the platform.

**Comment by sympmarc** [comment]
p.s. I tweeted out your article the other day, but couldn't find you on Twitter. Do you have a handle there?

**Comment by tomresing** [comment]
+1 on collaborative editing mode and twitter. On collaboration, what do you two think about the byline at the bottom of this article? I'm afraid it might discourage others to come in and make edits. @nyoung30 if you don't have a twitter account yet, I'd encourage it. Great resource for writers.
